Document: gobstones
Title: Debian gobstones Manual
Author: <insert document author here>
Abstract: This manual describes what gobstones is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gobstones/gobstones.sgml.gz

Format: postscript
Files: /usr/share/doc/gobstones/gobstones.ps.gz

Format: text
Files: /usr/share/doc/gobstones/gobstones.text.gz

Format: HTML
Index: /usr/share/doc/gobstones/html/index.html
Files: /usr/share/doc/gobstones/html/*.html
